pipeline {
    agent any
    environment {
        BUILD_NAME = "jenkins-${env.JOB_NAME}-${env.BUILD_NUMBER}"
        LT_BUILD_NAME = "${BUILD_NAME}"
        LAMBDA_CREDS = credentials('lt-creds')
    }
    stages {
        stage('Cleanup Workspace') {
            steps {
                deleteDir()
            }
        }
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Debug - Check Files') {
            steps {
                sh 'pwd'
                sh 'ls -R'
            }
        }
        stage('Restore Dependencies') {
            steps {
                sh '/usr/local/bin/dotnet restore TestProject1.sln'
            }
        }
        stage('Build') {
            steps {
                sh '/usr/local/bin/dotnet build TestProject1.sln --configuration Release'
            }
        }
        stage('Test') {
            steps {
                withEnv(["LT_USERNAME=${env.LAMBDA_CREDS_USR}", "LT_ACCESS_KEY=${env.LAMBDA_CREDS_PSW}", "LT_BUILD_NAME=${env.BUILD_NAME}"]) {
                    sh '/usr/local/bin/dotnet test TestProject1.sln'
                }
            }
        }
    }
    post {
        always {
            lambdaTestReportPublisher 'automation'
        }
    }
}
