pipeline {
    agent any
    environment {
        BUILD_NAME = "jenkins-${env.JOB_NAME}-${env.BUILD_NUMBER}"
        LT_BUILD_NAME = "${BUILD_NAME}"
    }
    stages {
        stage('Cleanup Workspace') {
            steps {
                deleteDir()
            }
        }
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Debug - Check Files') {
            steps {
                sh 'pwd'
                sh 'ls -R'
            }
        }
        stage('Restore Dependencies') {
            steps {
                sh '/usr/local/bin/dotnet restore TestProject1.sln'
            }
        }
        stage('Build') {
            steps {
                sh '/usr/local/bin/dotnet build TestProject1.sln --configuration Release'
            }
        }
        stage('Test') {
            steps {
                withEnv([
                    "LT_USERNAME=${sh(script: 'printenv LT_USERNAME', returnStdout: true).trim()}",
                    "LT_ACCESS_KEY=${sh(script: 'printenv LT_ACCESS_KEY', returnStdout: true).trim()}",
                    "LT_BUILD_NAME=${env.BUILD_NAME}"
                ]) {
                    sh '/usr/local/bin/dotnet test TestProject1.sln'
                }
            }
        }
    }
    post {
        always {
            lambdaTestReportPublisher 'automation'
        }
    }
}
